### ISSUE TITLE
don't work move_card to another board

### ISSUE THREAD

**Issue by sergeimonakhov** [StackStorm-Exchange/stackstorm-trello#6]
hi, i get error
`Traceback (most recent call last):
  File "/opt/stackstorm/runners/python_runner/python_runner/python_action_wrapper.py", line 320, in <module>
    obj.run()
  File "/opt/stackstorm/runners/python_runner/python_runner/python_action_wrapper.py", line 179, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/trello/actions/move_card.py", line 10, in run
    card.change_list(list_id=target_list_id)
  File "/opt/stackstorm/virtualenvs/trello/lib/python2.7/site-packages/trello/card.py", line 339, in change_list
    post_args={'value': list_id})
  File "/opt/stackstorm/virtualenvs/trello/lib/python2.7/site-packages/trello/trelloclient.py", line 190, in fetch_json
    raise ResourceUnavailable("%s at %s" % (response.text, url), response)
trello.exceptions.ResourceUnavailable: invalid id at https://api.trello.com/1/cards/5b587d71e1c5ac2a94244ca9/idList (HTTP status: 400)`
some help?
move card on one board work perfect

**Comment by LindsayHill** [comment]
It looks like you're getting an error from Trello, saying that ID doesn't exist. Have you checked the ID of the board you are trying to move to?

**Comment by sergeimonakhov** [comment]
yes, list is in another board, you need use another [metod](https://github.com/sarumont/py-trello/blob/622f76e62c327e506d231a07743e583081d72b96/trello/card.py#L682) for move card to another board

**Comment by LindsayHill** [comment]
OK, can you submit a PR to update that?
